### ISSUE TITLE
Config schema definition of graphql server and exported config doesn't match

### ISSUE THREAD

**Issue by chrfritsch** [drupal-graphql/graphql#1177]
We have an exported config that looks like this:

```
langcode: en
status: true
dependencies: {  }
name: thunder_graphql
label: 'Thunder - GraphQL Server'
schema: composable
schema_configuration:
  composable:
    extensions:
      thunder_paragraphs: thunder_paragraphs
      thunder_media: thunder_media
      thunder_routing: thunder_routing
      thunder_pages: thunder_pages
persisted_queries_settings: {  }
endpoint: /graphql
debug_flag: 0
caching: true
batching: true
```

There are two problems with this config:

1. The `schema_configuration` doesn't match the schema definition

```
    schema_configuration:
      type: 'graphql.schema.[%parent.schema]'
```
The schema definition needs to be this to match::
```
    schema_configuration:
      type: mapping
      label: 'Schema config'
      mapping:
        composable:
          label: Composable schema
          type: graphql.schema.composable
```
Or the exported config structure has to change.

2. The sequence in `graphql.schema.composable` is defined as boolean but it's exported as strings
```
schema_configuration:
  composable:
    extensions:
      thunder_paragraphs: thunder_paragraphs
      thunder_media: thunder_media
      thunder_routing: thunder_routing
      thunder_pages: thunder_pages
```

I think that should be changed to
```
schema_configuration:
  composable:
    extensions:
      thunder_paragraphs: true
      thunder_media: true
      thunder_routing: true
      thunder_pages: true
```
