### ISSUE TITLE
[question] simple query example with articles

### ISSUE THREAD

**Issue by yann-yinn** [drupal-graphql/graphql#134]
Hello ! I'm a   @#noob trying to explore graphQL with D8, i would like to get 10 nodes articles with their tags as **objects**, but instead of taxonomy terms i got a string. What should i do to get taxonomy terms objects ? 

Here is my query : 
```
{
  nodeQuery(offset:0, limit:10, filter:{type:"article"}) {
    entities {
      entityLabel
      entityId
      entityBundle
      fieldTags
    }
  }
}
```

And is it possible to have all articles with a particular referenced tag or i need to create a custom graphQL query ? 

PS : my goal is to recreate my wordpress blog website with D8 + graphQL + Nuxt.js => so i try to get the classic structure of a wordpress blog

Thanks

**Comment by pmelab** [comment]
To get the related tags as objects simply enable the `graphql_entity_reference` submodule and use "Rendered entity" as the fields formatter in your `default` or `graphql` view mode.

 For the articles-by-tag requirement, enable `graphql_views` and create a view with a filter for taxonomy terms and a *GraphQL* display. This view will be available as a root level field with and all exposed filters as arguments.

```
{
  myViewMyDisplay(filters: {tid: "3"}) {
  ...
  }
}
```

GraphQL explorer should tell you the specifics ...

**Comment by yann-yinn** [comment]
when i choose "rendered entity" i still got a html "string" for my fieldTags. Also I didn't saw a _graphQL_ view mode available nor a "_GraphQL display_" one for views :-/  I enabled **ALL** available graphQL modules to be sure and empty the cache three times.
<img width="678" alt="output" src="https://cloud.githubusercontent.com/assets/335495/26733614/a6c6cb62-47bb-11e7-98ec-1b26122e6f5a.png">
<img width="1379" alt="view_mode" src="https://cloud.githubusercontent.com/assets/335495/26733678/dba9a638-47bb-11e7-9b4a-02b260920634.png">
<img width="685" alt="view-displays" src="https://cloud.githubusercontent.com/assets/335495/26733688/e2199082-47bb-11e7-8141-c27c0de1b6a3.png">

any thoughts on this ?

**Comment by pmelab** [comment]
The output of *fieldTags*  looks like you didn't enable the `graphql_entity_reference` module.

And the `graphql_views` provides a display plugin (like *Page* or *Block*), not a Style plugin.

**Comment by yann-yinn** [comment]
ha okay sorry for display plugin. Graphgl_entity_reference is enabled, i will try to investigate code to figure out why this does not work as expected. 

<img width="1387" alt="enabled-modules" src="https://cloud.githubusercontent.com/assets/335495/26747434/05d95112-47f6-11e7-904a-a3a1068757c9.png">

**Comment by pmelab** [comment]
Which view modes did you configure for articles? Right now the modules tries to use `graphql` first and if its not available `default` (there's issue #86  to make this configurable). Perhaps "Rendered entity" is set in `default` but the api uses `graphql`?

**Comment by yann-yinn** [comment]
Hey thanks for all your help ! Yes i use "default" as far as i can see; and i can not see "graphgl" view mode available anywhere :-/

<img width="1376" alt="view_modes2" src="https://cloud.githubusercontent.com/assets/335495/26752483/4f8bd72a-4851-11e7-9eff-d3d67fe5402e.png">

<img width="1205" alt="all_view_modes" src="https://cloud.githubusercontent.com/assets/335495/26752484/5166999a-4851-11e7-8787-da4db2d87d61.png">

**Comment by pmelab** [comment]
Hm, thats weird. We've been using this feature a lot. The `graphql` view mode is not there by default. You can create it if your `default` view mode is required for something else. At least thats how it's supposed to be, perhaps it doesn't work properly. Could you try to create a view mode with machine name `graphql` (mind the *q* at the end, its not a *g*) and configure the field there?

**Comment by yann-yinn** [comment]
yes it worked as soon as i added "graphql" display mode on content entities !

<img width="880" alt="references-working" src="https://cloud.githubusercontent.com/assets/335495/26753192/3d1a4aa8-4861-11e7-98e2-a78bdf80e2c5.png">

**Comment by pmelab** [comment]
Awesome! Thanks for debugging 😬 ! Will keep this in mind when implementing #86.

**Comment by yann-yinn** [comment]
One last question ! I successfully created a custom query using view, but did not manage to use exposed filters as arguments . Here are two screens, with and without filtering.
<img width="880" alt="customqueryview" src="https://cloud.githubusercontent.com/assets/335495/26753478/74ad7d04-4867-11e7-9707-0c3f1ae01893.png">
<img width="984" alt="customqueryargumentsbroken" src="https://cloud.githubusercontent.com/assets/335495/26753479/7706b85e-4867-11e7-9b5b-7c24346d1c20.png">

PS : graphexplorer does not give autocompleting about fieldTags or my custom view Query, so i have to write things without knowing related schema behind the scene

**Comment by pmelab** [comment]
GraphQL explorer should be fine. On the righthand side there is a panel where you can search the schema for everything. This should also tell you about arguments.
If you configure the view with a pager, it should expose arguments for page and pagesize too.

**Comment by chuongle** [comment]
@pmelab I was able to pull out term referenced as object by adding the `graphql` view mode to Content Entity. However I can't do the same thing for content referenced. How do I make both content referenced and taxonomy term referenced both return as object?

@nyl-auster Are you able to figure out the view? I am having the same issue. I wrap around the view the query and pass in a specific id. However it does not return me anything.

Thanks

**Comment by yann-yinn** [comment]
@chuongle not for the moment, maybe i made a mistake building my view, here is its yml export : 

<details>
  <summary>Click to expand</summary>

```
uuid: 762ca784-1f6b-4250-8553-cab146ca7439
langcode: en
status: true
dependencies:
  config:
    - taxonomy.vocabulary.tags
  module:
    - graphql_views
    - node
    - taxonomy
    - user
id: articlesbytag
label: articlesByTag
module: views
description: ''
tag: ''
base_table: node_field_data
base_field: nid
core: 8.x
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: 0
    display_options:
      access:
        type: perm
        options:
          perm: 'access content'
      cache:
        type: tag
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: mini
        options:
          items_per_page: 10
          offset: 0
          id: 0
          total_pages: null
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      style:
        type: default
        options:
          grouping: {  }
          row_class: ''
          default_row_class: true
          uses_fields: false
      row:
        type: fields
        options:
          inline: {  }
          separator: ''
          hide_empty: false
          default_field_elements: true
      fields:
        title:
          id: title
          table: node_field_data
          field: title
          entity_type: node
          entity_field: title
          label: ''
          alter:
            alter_text: false
            make_link: false
            absolute: false
            trim: false
            word_boundary: false
            ellipsis: false
            strip_tags: false
            html: false
          hide_empty: false
          empty_zero: false
          settings:
            link_to_entity: true
          plugin_id: field
          relationship: none
          group_type: group
          admin_label: ''
          exclude: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_alter_empty: true
          click_sort_column: value
          type: string
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
      filters:
        tid:
          id: tid
          table: taxonomy_index
          field: tid
          relationship: none
          group_type: group
          admin_label: ''
          operator: or
          value: {  }
          group: 1
          exposed: true
          expose:
            operator_id: tid_op
            label: 'Has taxonomy term'
            description: ''
            use_operator: false
            operator: tid_op
            identifier: tid
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              administrator: '0'
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          reduce_duplicates: false
          type: textfield
          limit: true
          vid: tags
          hierarchy: false
          error_message: true
          plugin_id: taxonomy_index_tid
      sorts:
        changed:
          id: changed
          table: node_field_data
          field: changed
          relationship: none
          group_type: group
          admin_label: ''
          order: ASC
          exposed: false
          expose:
            label: ''
          granularity: second
          entity_type: node
          entity_field: changed
          plugin_id: date
      header: {  }
      footer: {  }
      empty: {  }
      relationships: {  }
      arguments: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - user
        - 'user.node_grants:view'
        - user.permissions
      tags: {  }
  graphql_1:
    display_plugin: graphql
    id: graphql_1
    display_title: GraphQL
    position: 1
    display_options:
      display_extenders: {  }
      exposed_form:
        type: graphql
        options:
          submit_button: Apply
          reset_button: 0
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: 1
          sort_asc_label: Asc
          sort_desc_label: Desc
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - user
        - 'user.node_grants:view'
        - user.permissions
      tags: {  }
```


</details>
