### ISSUE TITLE
Split graphql_content.schema.yml

### ISSUE THREAD

**Issue by Pasqualle** [drupal-graphql/graphql#262]
The exposed content configuration is stored in graphql_content.schema config as one big array. This is not good for various reasons:
- The default configuration is not easily included in custom modules.
- Parts of the configuration are not deleted when dependent module/configuration is deleted.

for example the **graphql_content.schema.yml** currently looks like
```
node:
    exposed: true
    bundles:
      article:
        exposed: true
        view_mode: node.graphql
      page:
        exposed: false
        view_mode: '0'
```

this should be split to:
**graphql.exposed.node.article.yml**
```
dependencies:
  config:
    - node.type.article
exposed: true
view_mode: node.graphql
```

**graphql.exposed.node.page.yml**
```
dependencies:
  config:
    - node.type.page
exposed: false
view_mode: '0'
```

~~The node.exposed value should be calculated from the bundles.~~

**graphql.exposed.node.yml**
```
dependencies:
  module:
    - node
exposed: true
```
